spring.application=name: dashboard
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
jwt.secrete=lzML23TY4X4Q8ePfWKWq60WZIKj68e5FRmbH7HgpP13
cors.allowed-origins=http://localhost:8080/ , *
